CREATE TABLE `docker-php`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


INSERT INTO `docker-php`.`users` (`name`, `desc`) VALUES
('John Smith', 'User 1 description'),
('Mary Johnson', 'User 2 description'),
('James Brown', 'User 3 description'),
('Linda Davis', 'User 4 description'),
('Jennifer Wilson', 'User 5 description'),
('Robert Lee', 'User 6 description'),
('Patricia Moore', 'User 7 description'),
('Michael Taylor', 'User 8 description'),
('Susan Anderson', 'User 9 description'),
('William Thomas', 'User 10 description'),
('Elizabeth Hall', 'User 11 description'),
('David Jackson', 'User 12 description'),
('Karen White', 'User 13 description'),
('Richard Harris', 'User 14 description'),
('Nancy Martin', 'User 15 description'),
('Joseph Clark', 'User 16 description'),
('Linda Lewis', 'User 17 description'),
('Charles Walker', 'User 18 description'),
('Sarah King', 'User 19 description'),
('Thomas Scott', 'User 20 description'),
('Margaret Young', 'User 21 description'),
('Christopher Turner', 'User 22 description'),
('Dorothy Baker', 'User 23 description'),
('Daniel Green', 'User 24 description'),
('Betty Evans', 'User 25 description'),
('Paul Edwards', 'User 26 description'),
('Alice Harris', 'User 27 description'),
('Mark Robinson', 'User 28 description'),
('Linda Lewis', 'User 29 description'),
('James Turner', 'User 30 description'),
('Sandra King', 'User 31 description'),
('Frank Wilson', 'User 32 description'),
('Donna Clark', 'User 33 description'),
('Eric Davis', 'User 34 description'),
('Carol Harris', 'User 35 description'),
('George White', 'User 36 description'),
('Ruth Taylor', 'User 37 description'),
('Jerry Young', 'User 38 description'),
('Patricia Lewis', 'User 39 description'),
('Kenneth Lee', 'User 40 description'),
('Cynthia Hall', 'User 41 description'),
('Steven Young', 'User 42 description'),
('Nancy Wright', 'User 43 description'),
('Edward Smith', 'User 44 description'),
('Dorothy Turner', 'User 45 description'),
('Brian King', 'User 46 description'),
('Donna Hall', 'User 47 description'),
('Timothy Baker', 'User 48 description'),
('Linda Lee', 'User 49 description'),
('Thomas Anderson', 'User 50 description');
